site_name: Wiki АИС Мосгорнаследия
theme:
  logo: assets/logo.png
  name: 'material'
  language: ru
  features:
    - navigation.tabs
    - toc.integrate 
  
plugins:
  - search:
      lang: 
        - ru
        - en
  - tags:
      tags_file: tags.md
  - mkdocs-video:
      # css_style:
      #   width: "100%"
      #   height: "100%"
  - awesome-pages
extra:
  homepage: http://172.22.119.132:8001/Wiki/Информация%20о%20системе/Аварийные%20ситуации/#_1
  social:
    - icon: fontawesome/brands/twitter  
      link: https://twitter.com/squidfunk
copyright: Copyright &copy; 2006-2022 ООО "АНСЕР ПРО"